export const FETCHING_MOVIES = 'FETCHING_MOVIES';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const FETCH_MOVIES_ERROR = 'FETCH_MOVIES_ERROR';
export const FETCHING_MORE_MOVIES = 'FETCHING_MORE_MOVIES';
export const FETCH_MORE_MOVIES_SUCCESS = 'FETCH_MORE_MOVIES_SUCCESS';
export const FETCH_MORE_MOVIES_ERROR = 'FETCH_MORE_MOVIES_ERROR';
export const SET_TOTAL_PAGES = 'SET_TOTAL_PAGES';
